import type { Metadata } from "next";

// The one public host. The apex (kairoslearn.com) redirects here, so every
// canonical, og:url, sitemap entry and robots Sitemap line must use this.
export const SITE_URL = "https://www.kairoslearn.com";
export const SITE_NAME = "KairosLearn";

type PageMetadataInput = {
  /** Bare page title. The root layout's title template appends " | KairosLearn". */
  title: string;
  description: string;
  /** Path on the site, starting with "/" ("/" for the homepage). */
  path: string;
  /** Keep the page out of search results (it can still be linked to). */
  noindex?: boolean;
  /** Use `title` as written, with no " | KairosLearn" suffix (the homepage). */
  absoluteTitle?: boolean;
};

// The site-wide preview image, generated by src/app/opengraph-image.tsx.
const PREVIEW_IMAGE = `${SITE_URL}/opengraph-image`;

// Next replaces (does not merge) a child's openGraph/twitter, so each page
// states its own url, title, description and image instead of inheriting the
// homepage's. Without the explicit image, shared links lost their preview.
export function pageMetadata({ title, description, path, noindex, absoluteTitle }: PageMetadataInput): Metadata {
  const url = `${SITE_URL}${path}`;
  const fullTitle = absoluteTitle ? title : `${title} | ${SITE_NAME}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website", locale: "en_US", siteName: SITE_NAME, url, title: fullTitle, description,
      images: [{ url: PREVIEW_IMAGE, width: 1200, height: 630, alt: SITE_NAME }],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [PREVIEW_IMAGE] },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}
