export const ENGLISH_650 = `On Monday morning, our school library smelled of damp coats and the lemon cleaner used over the weekend. I arrived early to help arrange a small community reading afternoon. The librarian, Ms. Rivera, handed me a clipboard, then pointed toward three boxes beside the returns desk. I expected books. Inside were extension cables, folded maps, and paper cups. Before anyone could read comfortably, somebody had to solve several ordinary problems that had nothing to do with reading.

Our first disagreement concerned the chairs. I drew neat rows facing the window because that arrangement looked calm on paper. Sam noticed that afternoon sunlight would shine directly into the readers' eyes. Noura asked where a wheelchair could turn without moving a table. We pushed everything aside and walked through the empty space together. The resulting layout looked less symmetrical than my drawing, but each person could enter, choose a seat, and leave without asking someone else to move.

At lunchtime, a younger student brought a torn picture book to the desk. He apologized before explaining that his little brother had pulled the cover loose. I nearly began describing our repair supplies. Ms. Rivera first asked whether the brother had enjoyed the story. The student's shoulders relaxed as he described the pictures. Later, while we fitted a protective sleeve around the cover, I understood that repairing an object and welcoming its owner were separate tasks requiring different kinds of attention.

Tuesday's planning meeting lasted longer than expected. We had advertised a quiet reading hour, yet several families wanted children to discuss stories aloud. A volunteer suggested separate rooms, but the smaller room was already reserved for homework help. We settled on two periods, with a short break between them. I rewrote the notice using larger letters and fewer instructions. When we showed it to people passing the desk, their questions revealed two ambiguities that our group had overlooked.

The afternoon began with a missing kettle and an unexpected delivery of magazines. Neither problem was dramatic, though both interrupted the schedule I had carefully numbered. I asked another volunteer to sort the magazines while I checked the staff kitchen. There was no kettle available, so we offered water instead of tea. Nobody complained. Looking at the abandoned schedule afterward, I realized that I had confused preparation with the ability to control every detail of an unfamiliar event.

During the discussion period, a grandfather described reading newspapers aloud to his neighbors many years earlier. A child asked why they had shared one newspaper instead of buying separate copies. His answer moved from money to friendship and then to the pleasure of arguing about the same story. I had prepared questions about favorite characters, but none seemed useful at that moment. I put down my list and listened while the conversation followed a direction nobody had planned.

After everyone left, we counted cups, returned chairs, and checked beneath the tables for forgotten belongings. We found a blue glove, a pencil case, and a shopping list written on the back of an envelope. The room looked ordinary again. My notes, however, no longer described only tasks completed. I recorded which signs confused visitors, where conversation became difficult to hear, and which small changes allowed people to participate without drawing attention to themselves.

On Wednesday, our team reviewed those notes before arranging another afternoon. We kept the wide entrance, changed the discussion timetable, and decided to ask visitors what they needed before proposing improvements. I still enjoy making clear plans, but I now leave space beside each item for an observation or a question. That empty space reminds me that a useful plan can change when other people enter the room. At the bottom, I added a reminder to check the lost property box before opening. Practical details still mattered; listening more carefully had simply changed which details I noticed and whose comfort I considered while quietly preparing.`;

export const URDU_650 = `پیر کی صبح میں اسکول کی لائبریری پہنچا تو کھڑکیوں کے پاس بارش کے چھوٹے قطرے چمک رہے تھے۔ ہماری جماعت نے محلے کے بچوں اور بڑوں کے لیے مطالعے کی ایک نشست رکھنے کا فیصلہ کیا تھا۔ میں نے سوچا تھا کہ میرا کام صرف کتابیں ترتیب دینا ہوگا، مگر پہلے ہی گھنٹے میں کئی دوسری ذمہ داریاں سامنے آگئیں۔

لائبریرین نے مجھے ایک خاکہ دیا جس پر میزوں کی جگہ نشان زد تھی۔ میں نے کرسیاں سیدھی قطاروں میں لگانا شروع کردیں۔ سمیرا نے پوچھا کہ اگر کوئی بزرگ چھڑی کے ساتھ آئیں تو ان کے گزرنے کی جگہ کہاں ہوگی۔ جو راستہ کاغذ پر کافی چوڑا لگ رہا تھا، حقیقت میں تنگ نکلا۔ ہم نے ترتیب بدلی اور دروازے کے قریب کھلی جگہ چھوڑ دی۔

دوسرے وقفے میں ایک بچہ پھٹی ہوئی کتاب لے کر آیا۔ وہ بار بار کہہ رہا تھا کہ صفحہ جان بوجھ کر نہیں پھاڑا گیا۔ میں فوراً مرمت کا سامان ڈھونڈنے لگا، لیکن لائبریرین نے پہلے اس سے کہانی کے بارے میں پوچھا۔ بچے نے ایک مضحکہ خیز تصویر دکھائی اور ہنسنے لگا۔ پھر ہم نے کاغذ احتیاط سے جوڑا۔ مجھے محسوس ہوا کہ کتاب کی مرمت سے پہلے اس بچے کی گھبراہٹ کم کرنا ضروری تھا۔

دوپہر کو رضاکاروں کی مختصر ملاقات ہوئی۔ کچھ لوگ خاموش مطالعہ چاہتے تھے، جبکہ دوسرے بچوں کو سوال کرنے کی آزادی دینا چاہتے تھے۔ ہمارے پاس صرف ایک بڑا کمرہ تھا۔ کافی گفتگو کے بعد ہم نے وقت کو دو حصوں میں بانٹ دیا۔ پہلے سب خاموشی سے پڑھیں گے اور پھر اپنی پسند کی بات بتائیں گے۔ میں نے اطلاع دوبارہ لکھی، مگر اس مرتبہ مشکل الفاظ کی جگہ سادہ جملے استعمال کیے۔

اگلے دن ہم نے وہ اطلاع چند آنے والوں کو دکھائی۔ ایک خاتون نے پوچھا کہ کیا چھوٹے بچوں کے ساتھ بیٹھنا ممکن ہوگا۔ ایک طالب علم کو نشست شروع ہونے کا وقت واضح نہیں لگا۔ ان سوالوں سے معلوم ہوا کہ ہم جن باتوں کو ظاہر سمجھ رہے تھے، وہ دوسروں کے لیے واضح نہیں تھیں۔ ہم نے وقت نمایاں کیا اور یہ بھی لکھا کہ بچے اپنے گھر والوں کے ساتھ بیٹھ سکتے ہیں۔

نشست شروع ہونے سے کچھ دیر پہلے معلوم ہوا کہ پانی کے گلاس دوسرے کمرے میں رکھے ہیں۔ اسی دوران رسالوں کا ایک نیا ڈبہ پہنچ گیا۔ میری تیار کردہ فہرست میں ان دونوں کاموں کا ذکر نہیں تھا۔ میں نے ایک ساتھی سے رسالے سنبھالنے کو کہا اور خود گلاس لینے گیا۔ چھوٹی تبدیلیوں کے باوجود پروگرام شروع ہوسکتا تھا، بس ہمیں ایک دوسرے کی مدد قبول کرنا تھی۔

گفتگو کے حصے میں ایک بزرگ نے بتایا کہ وہ بچپن میں اپنے دوستوں کو اخبار پڑھ کر سناتے تھے۔ ایک لڑکی نے پوچھا کہ سب اپنا اخبار کیوں نہیں خرید لیتے تھے۔ جواب میں بزرگ نے خرچ کے ساتھ مل بیٹھنے کی خوشی کا بھی ذکر کیا۔ میرے پاس پہلے سے تیار سوال تھے، مگر اس گفتگو کے دوران انہیں پڑھنا مناسب نہیں لگا۔ میں نے فہرست بند کردی اور باقی لوگوں کی باتیں سننے لگا۔

جب آخری مہمان چلے گئے تو ہم نے میزیں صاف کیں اور کرسیوں کو واپس رکھا۔ ایک میز کے نیچے نیلا دستانہ ملا۔ کھڑکی کے پاس کسی کی چھوٹی پنسل رہ گئی تھی۔ ہم نے دونوں چیزیں گم شدہ سامان کے ڈبے میں رکھ دیں۔ کمرہ پہلے جیسا دکھائی دینے لگا، مگر میری نوٹ بک میں اب صرف مکمل ہونے والے کام نہیں تھے۔ میں نے لوگوں کے سوال اور اپنی غلط فہمیاں بھی درج کیں۔

بدھ کی صبح ہم نے اگلی نشست کے لیے وہ نوٹ دوبارہ پڑھے۔ گفتگو کے لیے تھوڑا زیادہ وقت رکھنے کی تجویز بھی قبول ہوئی۔ میں نے نئی فہرست بناتے ہوئے ہر کام کے آگے ایک خالی سطر چھوڑ دی۔ وہاں بعد میں کوئی مشاہدہ یا سوال لکھا جاسکتا تھا۔ اب مجھے لگتا ہے کہ منصوبہ تب زیادہ مفید ہوتا ہے جب اس میں دوسروں کی ضرورت سننے کی گنجائش باقی رہے۔`;
