/**
 * SAMPLE OUTPUT: Generated by following course-planning + lesson-planning + cs-exercises skills
 *
 * Course: Data Structures & Algorithms (Beginner)
 * Module: Hash Maps & Dictionaries
 * Domain: computer-science / data-science
 * Level: beginner
 * Voice Persona: Coach Alex
 *
 * This file demonstrates what the skill files produce when executed correctly.
 * Use this as the quality benchmark for all CS course generation.
 */

import { Module } from "../../src/data/types";

export const hashMapsModule: Module = {
  id: "hash-maps",
  title: "Hash Maps & Dictionaries",
  description:
    "Understand how hash maps work under the hood, master Python's dict, and learn the complement pattern that solves dozens of interview problems.",
  lessons: [
    // ─── Lesson 1: What Is a Hash Map? ───
    {
      id: "hash-map-intro",
      slug: "hash-map-intro",
      title: "What Is a Hash Map?",
      content: `## Why Hash Maps Matter

Imagine you're a librarian. Someone asks for a book. You have two options:

1. **Walk through every shelf** until you find it (linear search — slow)
2. **Check the catalog system** that tells you the exact shelf and position (hash map — fast)

A **hash map** (called a **dictionary** in Python, **HashMap** in Java) is that catalog system for your data. It lets you store and retrieve values by a key in **O(1) time** — constant time, no matter how much data you have.

<!-- voice:section_check concept="hash map is O(1) lookup" -->
## How It Works (Simplified)

A hash map uses a **hash function** to convert a key into an array index:

\`\`\`
key: "Alice" → hash("Alice") → 42 → store at index 42
key: "Bob"   → hash("Bob")   → 17 → store at index 17
\`\`\`

When you look up "Alice" later, the same hash function produces 42 again,
and you go straight to that index. No searching required.

### Python's Dictionary

\`\`\`python
# Creating a dictionary
phonebook = {
    "Alice": "555-0101",
    "Bob": "555-0102",
    "Charlie": "555-0103",
}

# Lookup: O(1) — instant, regardless of size
print(phonebook["Alice"])    # "555-0101"

# Check if key exists: O(1)
print("Alice" in phonebook)  # True

# Add a new entry: O(1)
phonebook["Diana"] = "555-0104"

# Delete an entry: O(1)
del phonebook["Bob"]
\`\`\`

<!-- voice:section_check concept="dict operations are all O(1)" -->
## The Big Picture

| Operation | List (unsorted) | Hash Map |
|-----------|----------------|----------|
| Search by value | O(n) | O(1) |
| Insert | O(1) append | O(1) |
| Delete by value | O(n) | O(1) |
| Check if exists | O(n) | O(1) |

That's the power of hash maps: **every common operation is O(1)**.

### When to Use a Hash Map

Use a dictionary when you need to:
- **Count things** (word frequencies, character counts)
- **Look things up fast** (phone book, cache, index)
- **Track what you've seen** (deduplication, complement finding)
- **Group items by a key** (anagrams, categories)

<!-- voice:key_insight insight="Whenever you need fast lookup by key, reach for a dictionary" -->

## Deeper Reading

- **Python Docs**: [dict](https://docs.python.org/3/library/stdtypes.html#dict) — official reference
- **Think Python, Ch. 11**: Allen Downey — excellent beginner-friendly explanation
- **Visualgo.net**: [Hash Table](https://visualgo.net/en/hashtable) — animated visualization
`,
      starterCode: `def build_phonebook(names, numbers):
    """
    Build a phonebook dictionary from parallel lists of names and numbers.

    Args:
        names: List of strings (names)
        numbers: List of strings (phone numbers)

    Returns:
        Dictionary mapping each name to their phone number

    Example:
        >>> build_phonebook(["Alice", "Bob"], ["555-0101", "555-0102"])
        {'Alice': '555-0101', 'Bob': '555-0102'}
    """
    # TODO: Create a dictionary from the two lists
    # Hint: You can loop through both lists together
    pass


def lookup(phonebook, name):
    """
    Look up a name in the phonebook. Return "Not found" if name doesn't exist.

    Args:
        phonebook: Dictionary mapping names to numbers
        name: Name to look up

    Returns:
        Phone number string, or "Not found"

    Example:
        >>> lookup({"Alice": "555-0101"}, "Alice")
        '555-0101'
        >>> lookup({"Alice": "555-0101"}, "Bob")
        'Not found'
    """
    # TODO: Return the number if name exists, otherwise "Not found"
    # Hint: Use the 'in' operator to check before accessing
    pass


# ─── Test Cases ───
# Do not modify below this line

pb = build_phonebook(["Alice", "Bob", "Charlie"], ["555-0101", "555-0102", "555-0103"])
print(pb)
# Expected: {'Alice': '555-0101', 'Bob': '555-0102', 'Charlie': '555-0103'}

print(lookup(pb, "Alice"))
# Expected: 555-0101

print(lookup(pb, "Diana"))
# Expected: Not found

print(build_phonebook([], []))
# Expected: {}
`,
      solutionCode: `def build_phonebook(names, numbers):
    """
    Build a phonebook dictionary from parallel lists of names and numbers.

    Args:
        names: List of strings (names)
        numbers: List of strings (phone numbers)

    Returns:
        Dictionary mapping each name to their phone number

    Time Complexity: O(n) — one pass through both lists
    Space Complexity: O(n) — storing n key-value pairs
    """
    phonebook = {}
    for i in range(len(names)):
        phonebook[names[i]] = numbers[i]
    return phonebook
    # Alternative (Pythonic): return dict(zip(names, numbers))


def lookup(phonebook, name):
    """
    Look up a name in the phonebook. Return "Not found" if name doesn't exist.

    Args:
        phonebook: Dictionary mapping names to numbers
        name: Name to look up

    Returns:
        Phone number string, or "Not found"

    Time Complexity: O(1) — dictionary lookup is constant time
    """
    if name in phonebook:
        return phonebook[name]
    return "Not found"
    # Alternative (Pythonic): return phonebook.get(name, "Not found")


# ─── Test Cases ───
# Do not modify below this line

pb = build_phonebook(["Alice", "Bob", "Charlie"], ["555-0101", "555-0102", "555-0103"])
print(pb)
# Expected: {'Alice': '555-0101', 'Bob': '555-0102', 'Charlie': '555-0103'}

print(lookup(pb, "Alice"))
# Expected: 555-0101

print(lookup(pb, "Diana"))
# Expected: Not found

print(build_phonebook([], []))
# Expected: {}
`,
    },

    // ─── Lesson 2: Counting with Dictionaries ───
    {
      id: "counting-with-dicts",
      slug: "counting-with-dicts",
      title: "Counting with Dictionaries",
      content: `## The Counting Pattern

One of the most common uses of a hash map is **counting occurrences**. How many
times does each word appear? How many of each character? What's the most common item?

This pattern shows up everywhere — from data analysis to interview problems.

<!-- voice:section_check concept="counting pattern with dictionaries" -->
## The Manual Way vs the Python Way

### Building a frequency counter manually:

\`\`\`python
text = "apple banana apple cherry banana apple"
words = text.split()

freq = {}
for word in words:
    if word in freq:
        freq[word] += 1
    else:
        freq[word] = 1

print(freq)  # {'apple': 3, 'banana': 2, 'cherry': 1}
\`\`\`

### The Pythonic shortcut — \`dict.get()\`:

\`\`\`python
freq = {}
for word in words:
    freq[word] = freq.get(word, 0) + 1
\`\`\`

\`get(key, default)\` returns the value if the key exists, or the default if it doesn't.
This eliminates the if/else check entirely.

### Even shorter — \`collections.Counter\`:

\`\`\`python
from collections import Counter
freq = Counter(words)
print(freq.most_common(2))  # [('apple', 3), ('banana', 2)]
\`\`\`

<!-- voice:key_insight insight="dict.get(key, 0) + 1 is the idiomatic Python counting pattern" -->

## Java Equivalent

\`\`\`java
Map<String, Integer> freq = new HashMap<>();
for (String word : words) {
    freq.put(word, freq.getOrDefault(word, 0) + 1);
}
// Java's getOrDefault is the equivalent of Python's dict.get()
\`\`\`

**Same pattern, different syntax.** Once you know the counting pattern, it works
in every language.

## When You Need Counting

- **Character frequency** for anagram detection
- **Word frequency** for text analysis
- **Vote counting** in elections data
- **Inventory tracking** in business applications

<!-- voice:exercise_intro difficulty="medium" hints_available="3" -->
## Try It Yourself

The exercise below asks you to build a frequency counter and find the most
common element. Think about the counting pattern before you start.
`,
      starterCode: `def char_frequency(text):
    """
    Count the frequency of each character in text (ignore spaces).

    Args:
        text: Input string

    Returns:
        Dictionary mapping each character to its count

    Example:
        >>> char_frequency("hello")
        {'h': 1, 'e': 1, 'l': 2, 'o': 1}
    """
    # TODO: Loop through each character, count with dict.get()
    # Hint: Skip spaces using an if check
    pass


def most_common(freq_dict):
    """
    Find the key with the highest value in a frequency dictionary.

    Args:
        freq_dict: Dictionary mapping items to their counts

    Returns:
        The key with the highest count, or None if dict is empty

    Example:
        >>> most_common({'a': 3, 'b': 1, 'c': 5})
        'c'
    """
    # TODO: Track the max count and corresponding key
    # Hint: Initialize max_count to 0 and best_key to None
    pass


# ─── Test Cases ───
# Do not modify below this line

print(char_frequency("hello world"))
# Expected: {'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}

print(char_frequency("aaa"))
# Expected: {'a': 3}

print(char_frequency(""))
# Expected: {}

print(most_common({'a': 3, 'b': 1, 'c': 5}))
# Expected: c

print(most_common({}))
# Expected: None
`,
      solutionCode: `def char_frequency(text):
    """
    Count the frequency of each character in text (ignore spaces).

    Time Complexity: O(n) — one pass through string
    Space Complexity: O(k) — k unique characters
    """
    freq = {}
    for char in text:
        if char != ' ':
            freq[char] = freq.get(char, 0) + 1
    return freq


def most_common(freq_dict):
    """
    Find the key with the highest value in a frequency dictionary.

    Time Complexity: O(n) — one pass through dictionary
    Space Complexity: O(1) — only tracking max
    """
    if not freq_dict:
        return None

    max_count = 0
    best_key = None
    for key, count in freq_dict.items():
        if count > max_count:
            max_count = count
            best_key = key
    return best_key
    # Alternative (Pythonic): return max(freq_dict, key=freq_dict.get)


# ─── Test Cases ───
# Do not modify below this line

print(char_frequency("hello world"))
# Expected: {'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}

print(char_frequency("aaa"))
# Expected: {'a': 3}

print(char_frequency(""))
# Expected: {}

print(most_common({'a': 3, 'b': 1, 'c': 5}))
# Expected: c

print(most_common({}))
# Expected: None
`,
    },

    // ─── Lesson 3: The Complement Pattern (Two Sum) ───
    {
      id: "complement-pattern",
      slug: "complement-pattern",
      title: "The Complement Pattern",
      content: `## The Most Important Hash Map Pattern

If you learn ONE hash map technique, learn this one. The **complement pattern**
is the foundation for dozens of coding interview questions.

<!-- voice:section_check concept="complement pattern idea" -->
## The Problem

Given an array of numbers and a target, find two numbers that add up to the target.

\`\`\`
Input:  nums = [2, 7, 11, 15], target = 9
Output: [0, 1]  (because nums[0] + nums[1] = 2 + 7 = 9)
\`\`\`

## The Brute Force (Slow)

Check every pair — O(n²):

\`\`\`python
# DON'T do this in an interview
def two_sum_brute(nums, target):
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                return [i, j]
    return [-1, -1]
\`\`\`

This checks n × (n-1) / 2 pairs. For an array of 10,000 elements,
that's ~50 million comparisons. We can do much better.

## The Insight

For each number, you already KNOW what its partner must be:

\`\`\`
If target = 9 and current number = 2
Then I need: 9 - 2 = 7  ← this is the "complement"
\`\`\`

So instead of checking every pair, ask: **"Have I already seen the complement?"**

A hash map answers that in O(1).

<!-- voice:section_check concept="complement = target minus current" -->
## The Solution

\`\`\`python
def two_sum(nums, target):
    seen = {}  # value → index

    for i, num in enumerate(nums):
        complement = target - num

        if complement in seen:       # O(1) lookup
            return [seen[complement], i]

        seen[num] = i                # Remember this number

    return [-1, -1]
\`\`\`

**Walk through it with [2, 7, 11, 15], target = 9:**

| Step | num | complement | seen so far | Found? |
|------|-----|-----------|-------------|--------|
| 0 | 2 | 7 | {} | No → add {2: 0} |
| 1 | 7 | 2 | {2: 0} | Yes! Return [0, 1] |

Two steps. Not 6 pairs. That's O(n) vs O(n²).

## Java Version

\`\`\`java
public int[] twoSum(int[] nums, int target) {
    Map<Integer, Integer> seen = new HashMap<>();
    for (int i = 0; i < nums.length; i++) {
        int complement = target - nums[i];
        if (seen.containsKey(complement)) {
            return new int[]{seen.get(complement), i};
        }
        seen.put(nums[i], i);
    }
    return new int[]{-1, -1};
}
\`\`\`

**Same pattern, same logic.** The hash map (dict/HashMap) is the key.

<!-- voice:key_insight insight="The complement pattern turns an O(n²) nested loop into an O(n) single pass using a hash map" -->

<!-- voice:exercise_intro difficulty="medium" hints_available="3" -->
## Try It Yourself

Implement the two_sum function using the complement pattern. Don't use the
brute force approach — use a dictionary for O(n) time.
`,
      starterCode: `def two_sum(nums, target):
    """
    Find two numbers in nums that add up to target. Return their indices.

    Args:
        nums: List of integers
        target: Target sum (integer)

    Returns:
        List of two indices [i, j] where nums[i] + nums[j] == target,
        or [-1, -1] if no pair exists

    Example:
        >>> two_sum([2, 7, 11, 15], 9)
        [0, 1]

    Must be O(n) time using a hash map — no nested loops.
    """
    # TODO: Use a dictionary to store numbers you've seen
    # For each number, calculate the complement (target - num)
    # Check if the complement is already in your dictionary
    pass


# ─── Test Cases ───
# Do not modify below this line

print(two_sum([2, 7, 11, 15], 9))
# Expected: [0, 1]

print(two_sum([3, 2, 4], 6))
# Expected: [1, 2]

print(two_sum([3, 3], 6))
# Expected: [0, 1]

print(two_sum([1, 2, 3], 10))
# Expected: [-1, -1]

print(two_sum([], 5))
# Expected: [-1, -1]
`,
      solutionCode: `def two_sum(nums, target):
    """
    Find two numbers in nums that add up to target. Return their indices.

    Time Complexity: O(n) — single pass through the array
    Space Complexity: O(n) — storing up to n entries in the hash map
    """
    seen = {}  # Maps value → index

    for i, num in enumerate(nums):
        complement = target - num

        if complement in seen:
            return [seen[complement], i]

        seen[num] = i

    return [-1, -1]


# ─── Test Cases ───
# Do not modify below this line

print(two_sum([2, 7, 11, 15], 9))
# Expected: [0, 1]

print(two_sum([3, 2, 4], 6))
# Expected: [1, 2]

print(two_sum([3, 3], 6))
# Expected: [0, 1]

print(two_sum([1, 2, 3], 10))
# Expected: [-1, -1]

print(two_sum([], 5))
# Expected: [-1, -1]
`,
    },

    // ─── Lesson 4: Module Checkpoint ───
    {
      id: "hash-maps-checkpoint",
      slug: "hash-maps-checkpoint",
      title: "Module Checkpoint: Hash Maps",
      content: `## Nice Work!

You've completed the Hash Maps module. Let's celebrate what you've learned
and make sure it's all solid before moving on.

<!-- voice:section_check concept="module recap" -->
## What You've Mastered

1. **Hash Map Basics** — O(1) insert, lookup, delete using dictionaries
2. **The Counting Pattern** — \`dict.get(key, 0) + 1\` for frequency counting
3. **The Complement Pattern** — turning O(n²) into O(n) with a hash map lookup

These three ideas solve a huge number of real-world and interview problems.

## Quick Quiz

**Question 1:** What is the time complexity of looking up a key in a Python dictionary?

A) O(n)
B) O(log n)
C) O(1)
D) O(n²)

**Question 2:** True or False: "A dictionary can have duplicate keys."

Statement: In Python, if you assign \`d["key"] = 1\` and then \`d["key"] = 2\`,
the dictionary will contain both values.

**Question 3:** Fill in the blank:

"To count occurrences of items, the Pythonic pattern is:
\`freq[item] = freq._____(item, 0) + 1\`"

**Question 4:** In your own words, explain WHY the complement pattern is O(n)
instead of O(n²). What makes the dictionary lookup the key to the optimization?

**Question 5:** Given this code:

\`\`\`python
data = [1, 2, 2, 3, 3, 3]
freq = {}
for x in data:
    freq[x] = freq.get(x, 0) + 1
\`\`\`

What does \`freq\` contain after execution?

A) \`{1: 1, 2: 1, 3: 1}\`
B) \`{1: 1, 2: 2, 3: 3}\`
C) \`{1: 0, 2: 1, 3: 2}\`
D) \`{3: 3, 2: 2, 1: 1}\`

## Voice Summary

After the quiz, your voice coach will ask you to summarize the key ideas
from this module in your own words. This is a conversation, not a test —
it helps reinforce what you've learned and personalize your learning path.

**What to mention:** How hash maps give O(1) lookup, the counting pattern,
and the complement pattern. But say it however makes sense to you.
`,
    },
  ],
};
```
