// React-PDF document for the recommender brag sheet. Server-side renders to
// a Buffer; the route streams it as application/pdf.
//
// Fields mirror the BragSheet JSON shape the LLM returns from
// /api/cc/recommenders/[id]/brag-sheet.
import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", lineHeight: 1.5 },
  h1: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  subtitle: { color: "#555", marginBottom: 12 },
  h2: {
    fontSize: 13,
    fontWeight: 700,
    marginTop: 16,
    marginBottom: 6,
    color: "#1a1a1a",
    borderBottom: "1pt solid #aaa",
    paddingBottom: 2,
  },
  para: { marginBottom: 8 },
  bullet: { marginLeft: 12, marginBottom: 3 },
});

export type BragSheetPdfData = {
  studentName: string;
  recommenderName: string;
  recommenderRole: string;
  recommenderSubject: string | null;
  introduction: string;
  academicHighlights: string[];
  activityHighlights: string[];
  personalQualities: string[];
  specificAnecdotes: string[];
  closingNote: string;
};

export function BragSheetDocument({ data }: { data: BragSheetPdfData }): React.ReactElement {
  const recHeader = data.recommenderSubject
    ? `For ${data.recommenderName} (${data.recommenderRole} · ${data.recommenderSubject})`
    : `For ${data.recommenderName} (${data.recommenderRole})`;

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>Brag sheet · {data.studentName}</Text>
        <Text style={styles.subtitle}>{recHeader}</Text>

        <Text style={styles.h2}>Introduction</Text>
        <Text style={styles.para}>{data.introduction}</Text>

        <Text style={styles.h2}>Academic highlights</Text>
        {data.academicHighlights.map((s, i) => (
          <Text key={i} style={styles.bullet}>• {s}</Text>
        ))}

        <Text style={styles.h2}>Activity highlights</Text>
        {data.activityHighlights.map((s, i) => (
          <Text key={i} style={styles.bullet}>• {s}</Text>
        ))}

        <Text style={styles.h2}>Personal qualities</Text>
        {data.personalQualities.map((s, i) => (
          <Text key={i} style={styles.bullet}>• {s}</Text>
        ))}

        <Text style={styles.h2}>Stories the recommender might reference</Text>
        {data.specificAnecdotes.map((s, i) => (
          <Text key={i} style={styles.bullet}>• {s}</Text>
        ))}

        <Text style={styles.h2}>What this recommendation should convey</Text>
        <Text>{data.closingNote}</Text>

        <View style={{ marginTop: 24 }}>
          <Text style={{ fontSize: 9, color: "#777", textAlign: "center" }}>
            Generated by KairosLearn · kairoslearn.com
          </Text>
        </View>
      </Page>
    </Document>
  );
}

export async function renderBragSheetPdf(data: BragSheetPdfData): Promise<Buffer> {
  return renderToBuffer(<BragSheetDocument data={data} />);
}
