/**
 * Discover cross-domain concept bridges between lessons.
 *
 * Run: npx tsx scripts/discover-bridges.ts
 *
 * Prerequisites:
 * 1. Run migration 007_lesson_embeddings.sql
 * 2. Run: npx tsx scripts/seed-embeddings.ts lessons
 * 3. MOONSHOT_API_KEY in .env.local (for bridge label generation)
 */

import { readFileSync } from "fs";

// Load .env.local
try {
  const envFile = readFileSync(".env.local", "utf-8");
  for (const line of envFile.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (!process.env[key]) process.env[key] = val;
  }
} catch {
  console.error("Could not read .env.local");
  process.exit(1);
}

async function main() {
  const { createAdminSupabase } = await import("../src/lib/supabase-auth");
  const supabase = createAdminSupabase();

  console.log("Fetching all lesson embeddings...\n");

  const { data: lessons, error } = await supabase
    .from("lesson_embeddings")
    .select("id, course_id, course_domain, title, embedding");

  if (error || !lessons) {
    console.error("Failed to fetch lessons:", error);
    process.exit(1);
  }

  console.log(`Found ${lessons.length} lessons. Discovering cross-domain bridges...\n`);

  // Group by domain
  const byDomain: Record<string, typeof lessons> = {};
  for (const l of lessons) {
    const d = l.course_domain || "general";
    if (!byDomain[d]) byDomain[d] = [];
    byDomain[d].push(l);
  }

  const domains = Object.keys(byDomain);
  console.log(`Domains: ${domains.join(", ")}\n`);

  // For each lesson, find top matches in OTHER domains using pgvector
  let bridgeCount = 0;
  const batchSize = 50;
  const bridges: any[] = [];

  for (const lesson of lessons) {
    const lessonDomain = lesson.course_domain || "general";

    // Query pgvector for most similar lessons NOT in the same domain
    const { data: matches } = await supabase.rpc("match_cross_domain_lessons", {
      query_embedding: lesson.embedding,
      exclude_domain: lessonDomain,
      match_count: 2,
      match_threshold: 0.65,
    }).then(r => r, () => ({ data: null }));

    // If RPC doesn't exist yet, use a raw approach
    if (!matches) {
      // Fallback: skip if RPC not available
      continue;
    }

    for (const match of matches) {
      bridges.push({
        lesson_a_id: lesson.id,
        lesson_a_course: lesson.course_id,
        lesson_a_domain: lessonDomain,
        lesson_b_id: match.id,
        lesson_b_course: match.course_id,
        lesson_b_domain: match.course_domain,
        similarity: match.similarity,
        bridge_label: null, // Will be generated by LLM in a separate pass
      });
      bridgeCount++;
    }

    if (bridgeCount % 20 === 0 && bridgeCount > 0) {
      console.log(`  ... ${bridgeCount} bridges found`);
    }

    // Insert in batches
    if (bridges.length >= batchSize) {
      await supabase.from("concept_bridges").upsert(bridges);
      bridges.length = 0;
    }

    await new Promise((r) => setTimeout(r, 50));
  }

  // Insert remaining
  if (bridges.length > 0) {
    await supabase.from("concept_bridges").upsert(bridges);
  }

  console.log(`\nDone: ${bridgeCount} cross-domain bridges discovered.`);

  // Generate bridge labels using Moonshot for top bridges
  console.log("\nGenerating bridge labels for top bridges...\n");

  const { data: topBridges } = await supabase
    .from("concept_bridges")
    .select("id, lesson_a_id, lesson_b_id, similarity")
    .is("bridge_label", null)
    .order("similarity", { ascending: false })
    .limit(50);

  if (topBridges && topBridges.length > 0 && process.env.MOONSHOT_API_KEY) {
    for (const bridge of topBridges) {
      const lessonA = lessons.find((l) => l.id === bridge.lesson_a_id);
      const lessonB = lessons.find((l) => l.id === bridge.lesson_b_id);
      if (!lessonA || !lessonB) continue;

      try {
        const resp = await fetch("https://api.moonshot.ai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.MOONSHOT_API_KEY}`,
          },
          body: JSON.stringify({
            model: "kimi-k2-turbo-preview",
            messages: [
              {
                role: "user",
                content: `These two lessons from different domains share a deep conceptual connection:

Lesson A (${lessonA.course_domain}): "${lessonA.title}"
Lesson B (${lessonB.course_domain}): "${lessonB.title}"

In one sentence (under 20 words), explain the surprising conceptual bridge between them. Start with "Both explore..." or "The same principle of..."`,
              },
            ],
            max_tokens: 60,
          }),
        });

        if (resp.ok) {
          const data = await resp.json();
          const label = data.choices?.[0]?.message?.content?.trim();
          if (label) {
            await supabase
              .from("concept_bridges")
              .update({ bridge_label: label })
              .eq("id", bridge.id);
            console.log(`  ✓ ${lessonA.title} ↔ ${lessonB.title}: ${label}`);
          }
        }
      } catch {
        // Skip label generation failures
      }

      await new Promise((r) => setTimeout(r, 300));
    }
  }

  console.log("\nBridge discovery complete!");
}

main().catch(console.error);
